// 疝鸡杯题库种子数据
// 题目均为真实事实、附可核验出处；correct 答案在玩家取题接口不下发（防作弊）。

export type QuizCategory = 'basic' | 'sugar';
export type QuizDifficulty = 'easy' | 'medium' | 'hard';

export interface QuizSeedItem {
  /** 题干 */
  stem: string;
  /** 4 个选项 */
  options: string[];
  /** 正确选项下标 0-3 */
  answerIndex: number;
  /** 分类：basic 基础常识 / sugar 糖点细节 */
  category: QuizCategory;
  /** 难度 */
  difficulty: QuizDifficulty;
  /** 出处链接 */
  sourceUrl: string;
  /** 出处说明 */
  sourceNote: string;
}

export const quizSeed: QuizSeedItem[] = [
  // ===================== Part A · 基础常识 =====================

  {
    stem: '名井南（Mina）的生日是？',
    options: ['1996-12-29', '1997-03-24', '1996-11-09', '1997-02-01'],
    answerIndex: 1,
    category: 'basic',
    difficulty: 'easy',
    sourceUrl: 'https://twice.jype.com/Mobile/Profile',
    sourceNote: 'JYP 官方 Profile',
  },
  {
    stem: '凑崎纱夏（Sana）的生日是？',
    options: ['1996-12-29', '1997-03-24', '1996-11-09', '1995-12-29'],
    answerIndex: 0,
    category: 'basic',
    difficulty: 'easy',
    sourceUrl: 'https://www.twicejapan.com/feature/profile',
    sourceNote: 'TWICE Japan 官方 Profile',
  },
  {
    stem: 'Mina 出生于？',
    options: ['日本大阪', '美国得克萨斯州圣安东尼奥', '日本神户', '美国洛杉矶'],
    answerIndex: 1,
    category: 'basic',
    difficulty: 'easy',
    sourceUrl: 'https://kprofiles.com/twice-members-profile/amp/',
    sourceNote: 'Kprofiles（父母为日本人，幼年搬回神户）',
  },
  {
    stem: 'Sana 出生于？',
    options: ['大阪市天王寺区', '大阪市中央区', '大阪府堺市', '神户市中央区'],
    answerIndex: 0,
    category: 'basic',
    difficulty: 'medium',
    sourceUrl: 'https://elle.com.sg/life-culture/twice-members-profile-2025/',
    sourceNote: 'ELLE Singapore',
  },
  {
    stem: '关于「37line」得名，下列哪项正确？',
    options: [
      '按年龄顺位，Sana 第 3、Mina 第 7',
      '两人名字的日语发音都能拼出 37：3 可读 Mi 或 Sa，7 读 Na',
      '两人在《The Feels》中的号码都选了 37',
      'CP 名取自 MISAMO 出道日 7 月 3 日',
    ],
    answerIndex: 1,
    category: 'basic',
    difficulty: 'hard',
    sourceUrl: 'https://www.koreaboo.com/stories/twice-reveals-favorite-numbers-special-meaning-behind/',
    sourceNote: 'Koreaboo（年龄顺位其实是 46；号码仅 Mina 为 37、Sana 为 12）',
  },
  {
    stem: 'Mina 出道前持续练习超过十年的是？',
    options: ['钢琴', '芭蕾', '跆拳道', '现代舞'],
    answerIndex: 1,
    category: 'basic',
    difficulty: 'easy',
    sourceUrl: 'https://kpopbio.com/twice-members-profile-bio/',
    sourceNote: 'Kpopbio',
  },
  {
    stem: 'Mina 的血型是？',
    options: ['A', 'B', 'O', 'AB'],
    answerIndex: 0,
    category: 'basic',
    difficulty: 'medium',
    sourceUrl: 'https://www.twicejapan.com/feature/profile',
    sourceNote: 'TWICE Japan 官方 Profile',
  },
  {
    stem: 'Sana 的血型是？',
    options: ['A', 'B', 'O', 'AB'],
    answerIndex: 1,
    category: 'basic',
    difficulty: 'medium',
    sourceUrl: 'https://www.twicejapan.com/feature/profile',
    sourceNote: 'TWICE Japan 官方 Profile',
  },
  {
    stem: 'Mina 的英文名是？',
    options: ['Sharon', 'Amy', 'Rachel', 'Lily'],
    answerIndex: 0,
    category: 'basic',
    difficulty: 'medium',
    sourceUrl: 'https://kprofiles.com/twice-members-profile/amp/',
    sourceNote: 'Kprofiles',
  },
  {
    stem: 'Mina 目前的法定国籍是？',
    options: ['美国', '日本（出生为美籍、2019 年放弃美籍）', '美日双重国籍', '加拿大'],
    answerIndex: 1,
    category: 'basic',
    difficulty: 'medium',
    sourceUrl: 'https://kprofiles.com/misamo-twice-j-line-sub-unit/',
    sourceNote: 'Kprofiles MISAMO Profile',
  },
  {
    stem: 'Mina 在团内的主要定位是？',
    options: ['Main Vocalist', 'Main Dancer / Sub Vocalist', 'Main Rapper', '队长'],
    answerIndex: 1,
    category: 'basic',
    difficulty: 'easy',
    sourceUrl: 'https://kprofiles.com/twice-members-profile/amp/',
    sourceNote: 'Kprofiles',
  },
  {
    stem: 'Sana 在团内的定位是？',
    options: ['Main Vocalist', 'Sub Vocalist', 'Main Dancer', 'Main Rapper'],
    answerIndex: 1,
    category: 'basic',
    difficulty: 'medium',
    sourceUrl: 'https://karchives.com/twice/',
    sourceNote: 'K-Archives',
  },
  {
    stem: 'Sana 尤其以什么闻名？',
    options: ['高音', '撒娇（aegyo）', 'Rap', '芭蕾'],
    answerIndex: 1,
    category: 'basic',
    difficulty: 'easy',
    sourceUrl: 'https://elle.com.sg/life-culture/twice-members-profile-2025/',
    sourceNote: 'ELLE Singapore',
  },
  {
    stem: 'Mina 的全名罗马音是？',
    options: ['Myoui Mina', 'Minatozaki Mina', 'Hirai Mina', 'Yoo Mina'],
    answerIndex: 0,
    category: 'basic',
    difficulty: 'medium',
    sourceUrl: 'https://kprofiles.com/twice-members-profile/amp/',
    sourceNote: 'Kprofiles',
  },
  {
    stem: 'Sana 的全名罗马音是？',
    options: ['Minatozaki Sana', 'Myoui Sana', 'Hirai Sana', 'Osaka Sana'],
    answerIndex: 0,
    category: 'basic',
    difficulty: 'medium',
    sourceUrl: 'https://kprofiles.com/twice-members-profile/amp/',
    sourceNote: 'Kprofiles',
  },
  {
    stem: 'TWICE 所属的经纪公司是？',
    options: ['SM', 'JYP', 'YG', 'HYBE'],
    answerIndex: 1,
    category: 'basic',
    difficulty: 'easy',
    sourceUrl: 'https://twice.jype.com/Mobile/Profile',
    sourceNote: 'JYP 官方',
  },
  {
    stem: 'TWICE 一共有几名成员？',
    options: ['7', '9', '12', '5'],
    answerIndex: 1,
    category: 'basic',
    difficulty: 'easy',
    sourceUrl: 'https://m.baike.com/wiki/TWICE/10414970',
    sourceNote: '抖音百科·TWICE',
  },
  {
    stem: 'TWICE 的出道日期是？',
    options: ['2015-10-20', '2015-05-05', '2016-10-20', '2017-10-26'],
    answerIndex: 0,
    category: 'basic',
    difficulty: 'easy',
    sourceUrl: 'https://twice.jype.com/discography/srviv59i',
    sourceNote: 'JYP 官网',
  },
  {
    stem: 'TWICE 的出道曲是？',
    options: ['CHEER UP', 'Like OOH-AHH（优雅地）', 'TT', 'Feel Special'],
    answerIndex: 1,
    category: 'basic',
    difficulty: 'easy',
    sourceUrl: 'http://korea.people.com.cn/n/2015/1022/c205178-8965646.html',
    sourceNote: '人民网韩国频道',
  },
  {
    stem: 'TWICE 的出道专辑是？',
    options: ['THE STORY BEGINS', 'Masterpiece', 'Twicetagram', 'STRATEGY'],
    answerIndex: 0,
    category: 'basic',
    difficulty: 'easy',
    sourceUrl: 'https://m.baike.com/wiki/TWICE/10414970',
    sourceNote: '抖音百科·TWICE',
  },
  {
    stem: 'TWICE 是通过哪档选秀节目成团的？',
    options: ['SIXTEEN', 'PRODUCE 101', 'KINGDOM', 'Show Me The Money'],
    answerIndex: 0,
    category: 'basic',
    difficulty: 'easy',
    sourceUrl: 'http://korea.people.com.cn/n/2015/1022/c205178-8965646.html',
    sourceNote: '人民网韩国频道',
  },
  {
    stem: 'TWICE 的官方粉丝名是？',
    options: ['ONCE', 'APRICOT', 'CANDY', 'MOMO'],
    answerIndex: 0,
    category: 'basic',
    difficulty: 'easy',
    sourceUrl: 'https://m.baike.com/wiki/TWICE/10414970',
    sourceNote: '抖音百科·TWICE',
  },
  {
    stem: 'MISAMO 由哪三位成员组成？',
    options: ['Mina / Sana / Momo', 'Mina / Sana / Jihyo', 'Mina / Momo / Nayeon', 'Sana / Momo / Dahyun'],
    answerIndex: 0,
    category: 'basic',
    difficulty: 'easy',
    sourceUrl: 'https://m.baike.com/wiki/MISAMO/7196996684769236279',
    sourceNote: '抖音百科·MISAMO',
  },
  {
    stem: 'MISAMO 的出道日期是？',
    options: ['2023-07-26', '2023-01-25', '2024-11-06', '2023-09-12'],
    answerIndex: 0,
    category: 'basic',
    difficulty: 'medium',
    sourceUrl: 'https://www.twicejapan.com/news/detail/1286',
    sourceNote: 'TWICE Japan 官网',
  },
  {
    stem: 'MISAMO 的出道专辑名是？',
    options: ['HAUTE COUTURE', 'Masterpiece', 'THE STORY BEGINS', 'STRATEGY'],
    answerIndex: 1,
    category: 'basic',
    difficulty: 'easy',
    sourceUrl: 'https://www.twicejapan.com/news/detail/1286',
    sourceNote: 'TWICE Japan 官网',
  },
  {
    stem: 'MISAMO 出道专辑的主打曲是？',
    options: ['Do not touch', 'Funny Valentine', 'Marshmallow', 'Bouquet'],
    answerIndex: 0,
    category: 'basic',
    difficulty: 'medium',
    sourceUrl: 'https://wmg.jp/twice/discography/28032/',
    sourceNote: 'Warner Music Japan / 官方曲目',
  },
  {
    stem: 'MISAMO 的第二张日本迷你专辑是？',
    options: ['Masterpiece', 'HAUTE COUTURE（2024-11-06）', 'TEN', 'Celebrate'],
    answerIndex: 1,
    category: 'basic',
    difficulty: 'medium',
    sourceUrl: 'https://www.twicejapan.com/discography/kind/5/',
    sourceNote: 'TWICE Japan Discography',
  },
  {
    stem: 'MISAMO 是 TWICE 的什么？',
    options: ['日本小分队（三名日籍成员）', '韩国分队', '独立二人组合', '唱片品牌'],
    answerIndex: 0,
    category: 'basic',
    difficulty: 'easy',
    sourceUrl: 'https://m.baike.com/wiki/MISAMO/7196996684769236279',
    sourceNote: '抖音百科·MISAMO',
  },
  {
    stem: '下列哪首歌收录在《Masterpiece》中？',
    options: ['Behind The Curtain', 'Like OOH-AHH', 'CHEER UP', 'TT'],
    answerIndex: 0,
    category: 'basic',
    difficulty: 'medium',
    sourceUrl: 'https://wmg.jp/twice/discography/28032/',
    sourceNote: 'Warner Music Japan 官方曲目',
  },
  {
    stem: '「MISAMO」这个名字的由来是？',
    options: ['MINA·SANA·MOMO 名字的开头字母', '日语“美丽”之意', '随机命名', '公司商标'],
    answerIndex: 0,
    category: 'basic',
    difficulty: 'medium',
    sourceUrl: 'https://m.baike.com/wiki/MISAMO/7196996684769236279',
    sourceNote: '抖音百科·MISAMO',
  },
  {
    stem: 'Mina 选择的幸运数字 37，是因为？',
    options: ['日语里 3=Mi、7=Na，合起来 Mina', '随便选的', '宿舍门牌号', '生日是 3 月 7 日'],
    answerIndex: 0,
    category: 'basic',
    difficulty: 'medium',
    sourceUrl: 'https://www.koreaboo.com/stories/twice-reveals-favorite-numbers-special-meaning-behind/',
    sourceNote: 'Koreaboo',
  },
  {
    stem: '《The Feels》相关号码中，Sana 最终选择的号码是？',
    options: ['12（出生月 12 月；原本想要 37 被 Mina 先选走）', '37', '7', '29'],
    answerIndex: 0,
    category: 'basic',
    difficulty: 'hard',
    sourceUrl: 'https://www.koreaboo.com/lists/hidden-meaning-behind-numbers-twice-feels-uniforms/',
    sourceNote: 'Koreaboo',
  },
  {
    stem: 'Mina 当初是怎么被 JYP 发掘的？',
    options: ['和妈妈逛街时被 JYP 选中', '学校比赛拿第一', '网上投稿视频', '舞蹈学院推荐'],
    answerIndex: 0,
    category: 'basic',
    difficulty: 'medium',
    sourceUrl: 'https://kpopbio.com/twice-members-profile-bio/',
    sourceNote: 'Kpopbio',
  },
  {
    stem: 'Mina 随父母搬回日本后，主要在哪里长大？',
    options: ['神户（兵库县）', '大阪', '东京', '京都'],
    answerIndex: 0,
    category: 'basic',
    difficulty: 'medium',
    sourceUrl: 'https://kprofiles.com/twice-members-profile/amp/',
    sourceNote: 'Kprofiles',
  },
  {
    stem: '2019—2020 年 Mina 曾经历什么？',
    options: [
      '因恐慌 / 焦虑障碍暂停活动，2020 年 2 月恢复日本日程',
      '从未暂停活动',
      '因腿伤暂停活动',
      '因感冒暂停活动',
    ],
    answerIndex: 0,
    category: 'basic',
    difficulty: 'medium',
    sourceUrl: 'http://m.toutiao.com/group/6779811638728983054/',
    sourceNote: 'JYP 官方立场（媒体转引）',
  },
  {
    stem: '下列哪一组作品都是 TWICE 在 2020 年推出的？',
    options: [
      'MORE & MORE / I CAN\'T STOP ME / CRY FOR ME',
      'Alcohol-Free / SCIENTIST',
      'Talk that Talk / Celebrate',
      'Do not touch / HAUTE COUTURE',
    ],
    answerIndex: 0,
    category: 'basic',
    difficulty: 'hard',
    sourceUrl: 'https://www.twiceland9.com/discography/',
    sourceNote: 'JYP 官网 / TWICELAND 年表',
  },
  {
    stem: '下列哪一组作品都是 TWICE 在 2021 年推出的？',
    options: [
      'Taste of Love（Alcohol-Free）/ The Feels / Formula of Love（SCIENTIST）',
      'MORE & MORE / CRY FOR ME',
      'Between 1&2 / Celebrate',
      'Masterpiece / HAUTE COUTURE',
    ],
    answerIndex: 0,
    category: 'basic',
    difficulty: 'hard',
    sourceUrl: 'https://twice.jype.com/discography/oj4hhlps',
    sourceNote: 'JYP 官网',
  },
  {
    stem: '下列哪一组作品是 TWICE 在 2022 年推出的？',
    options: [
      'Between 1&2（Talk that Talk）/ Celebrate',
      'Alcohol-Free / The Feels',
      'MORE & MORE / I CAN\'T STOP ME',
      'Masterpiece / Do not touch',
    ],
    answerIndex: 0,
    category: 'basic',
    difficulty: 'hard',
    sourceUrl: 'https://www.twiceland9.com/discography/',
    sourceNote: 'TWICELAND 年表 / Kprofiles',
  },

  // ===================== Part B · 糖点细节（2015—2017）=====================

  {
    stem: '出道前（2015-06-15）那张著名照片里，两人头上戴着什么？',
    options: ['颈枕（旅行头枕）', '生日帽', '耳机', '花环'],
    answerIndex: 0,
    category: 'sugar',
    difficulty: 'medium',
    sourceUrl: 'https://weibo.com/7767393204/5332703509744046',
    sourceNote: '「头戴颈枕的俩呆瓜」',
  },
  {
    stem: '2015-06-20 的名场面「狗压企鹅」，是谁压在谁身上？',
    options: ['Sana（柴犬）压在 Mina（企鹅）身上', 'Mina 压在 Sana 身上', 'Momo 压在两人身上', '两人并排躺着'],
    answerIndex: 0,
    category: 'sugar',
    difficulty: 'medium',
    sourceUrl: 'https://weibo.com/5261773804/3855803776022338',
    sourceNote: '「狗压企鹅」',
  },
  {
    stem: '2015 年 6 月被粉丝连称「天哪」的系列合照，最早一张是哪天？',
    options: ['2015-06-22', '2015-08-23', '2015-10-20', '2015-12-04'],
    answerIndex: 0,
    category: 'sugar',
    difficulty: 'hard',
    sourceUrl: 'https://weibo.com/5261773804/CnLJsfBnD',
    sourceNote: '「天哪合照」',
  },
  {
    stem: '2015-08-23 两人有一张什么场景的合照？',
    options: ['海边', '滑雪场', '图书馆', '演播室'],
    answerIndex: 0,
    category: 'sugar',
    difficulty: 'easy',
    sourceUrl: 'https://weibo.com/5261773804/3879058653520599',
    sourceNote: '「海边合照」',
  },
  {
    stem: '出道当天（2015-10-20）有一张怎样的合照？',
    options: ['backhug（背后抱）', '背对背', '击掌', '比心'],
    answerIndex: 0,
    category: 'sugar',
    difficulty: 'medium',
    sourceUrl: 'https://weibo.com/5689958174/3902939422748688',
    sourceNote: '出道日「backhug」',
  },
  {
    stem: '2015-11-02「两个笨蛋过马路」，形容的是两人怎样的状态？',
    options: ['傻乎乎地一起过马路', '在马路上跳舞', '迷路找不到公司', '撑同一把伞'],
    answerIndex: 0,
    category: 'sugar',
    difficulty: 'medium',
    sourceUrl: 'https://weibo.com/5689958174/D21MBkcR9',
    sourceNote: '「两个笨蛋过马路」',
  },
  {
    stem: '2015-12-04 被形容为「她逃、她追，她们都插翅难飞」，同一天还有哪组主题照？',
    options: ['爱神与花神', '初雪', '海边', '圣诞'],
    answerIndex: 0,
    category: 'sugar',
    difficulty: 'hard',
    sourceUrl: 'https://weibo.com/7767393204/QzytCCaYm',
    sourceNote: '「爱神与花神」',
  },
  {
    stem: '2015-12-05 的合照里两人在做什么动作？',
    options: ['比心', 'bobo', '掰手腕', '下腰'],
    answerIndex: 0,
    category: 'sugar',
    difficulty: 'easy',
    sourceUrl: 'https://weibo.com/5689958174/D79rpF1g2',
    sourceNote: '「比心」',
  },
  {
    stem: '2016-01-18，Sana 为 Mina 做了什么？',
    options: ['按摩', '梳头', '化妆', '做饭'],
    answerIndex: 0,
    category: 'sugar',
    difficulty: 'medium',
    sourceUrl: 'https://weibo.com/5261773804/DdGwNyIxV',
    sourceNote: '「纱给南按摩」',
  },
  {
    stem: '2016-03-17 名为「起飞！」的视频里，两人在做什么？',
    options: ['玩闹到像“起飞”一样被抱起', '坐飞机', '跳伞', '荡秋千'],
    answerIndex: 0,
    category: 'sugar',
    difficulty: 'medium',
    sourceUrl: 'https://weibo.com/5261773804/QCtOW8Wea',
    sourceNote: '「起飞！」',
  },
  {
    stem: '2016-05-01 的名场面被粉丝逐帧反复研究，主题是？',
    options: ['到底“亲没亲”', '谁赢了游戏', '谁先睡着', '谁拿了第一'],
    answerIndex: 0,
    category: 'sugar',
    difficulty: 'medium',
    sourceUrl: 'https://weibo.com/1745283033/KBPEz9neP',
    sourceNote: '「名场面之亲没亲」',
  },
  {
    stem: '2016-05-15「掰手腕一秒就输的狗」，说的是谁？',
    options: ['Sana（柴犬）一秒输给 Mina', 'Mina 一秒输给 Sana', 'Momo 赢了', '两人平手'],
    answerIndex: 0,
    category: 'sugar',
    difficulty: 'medium',
    sourceUrl: 'https://weibo.com/5261773804/DvN6I2P0l',
    sourceNote: '「掰手腕一秒就输的狗」',
  },
  {
    stem: '2016-05-22 的调皮名场面是？',
    options: ['Sana 抓 Mina（企鹅）的屁股', 'Mina 抓 Sana', '两人抢话筒', 'Sana 藏起 Mina 的鞋'],
    answerIndex: 0,
    category: 'sugar',
    difficulty: 'medium',
    sourceUrl: 'https://weibo.com/7315256980/MzO8N0jr8',
    sourceNote: '「狗抓企鹅屁股」',
  },
  {
    stem: '2016-05-29 被粉丝戏称「强制爱」的照片里发生了什么？',
    options: ['Sana 把 Mina 紧紧抱住 / 贴住', '两人吵架', 'Mina 拒绝合照', 'Momo 拉开两人'],
    answerIndex: 0,
    category: 'sugar',
    difficulty: 'medium',
    sourceUrl: 'https://weibo.com/5261773804/DxT2t1r4X',
    sourceNote: '「强制爱」',
  },
  {
    stem: '2016-06-18「偷亲被抓」名场面，是谁偷亲谁？',
    options: ['Sana 偷亲 Mina 被抓个正着', 'Mina 偷亲 Sana', 'Momo 偷亲两人', '其实是粉丝看错了'],
    answerIndex: 0,
    category: 'sugar',
    difficulty: 'medium',
    sourceUrl: 'https://weibo.com/5635875812/DAWL8xOqj',
    sourceNote: '「偷亲被抓」',
  },
  {
    stem: '与 2015 年「狗压企鹅」相反，2016-08-29 发生了什么？',
    options: ['企鹅（Mina）压狗（Sana）', '狗又压企鹅', '两人站着抱', 'Momo 压两人'],
    answerIndex: 0,
    category: 'sugar',
    difficulty: 'medium',
    sourceUrl: 'https://weibo.com/5689958174/E68eCl9Je',
    sourceNote: '「企鹅压狗」',
  },
  {
    stem: '「37line」这个称呼在站内日历中最早出现于？',
    options: ['2016-10-24', '2015-10-20', '2017-03-24', '2023-07-26'],
    answerIndex: 0,
    category: 'sugar',
    difficulty: 'hard',
    sourceUrl: 'https://weibo.com/7767393204/5332649826847071',
    sourceNote: '「37line」',
  },
  {
    stem: '被粉丝说要「带进坟墓」的名场面「最美初雪」发生在？',
    options: ['2016-11-26', '2015-12-04', '2017-02-19', '2018-02-22'],
    answerIndex: 0,
    category: 'sugar',
    difficulty: 'hard',
    sourceUrl: 'https://weibo.com/5635875812/EjnWarROC',
    sourceNote: '「最美初雪」',
  },
  {
    stem: '2017-02-19 名场面「下跪接花，下一步婚姻」，是谁向谁下跪？',
    options: ['Sana 向 Mina 下跪接花', 'Mina 向 Sana 下跪', '两人互相下跪', 'Momo 下跪'],
    answerIndex: 0,
    category: 'sugar',
    difficulty: 'medium',
    sourceUrl: 'https://weibo.com/5635875812/EwiXHmsZs',
    sourceNote: '「下跪接花」',
  },
  {
    stem: '2017-03-25（Mina 生日后），Mina 被谁 bobo 了？',
    options: ['被 Sana（夏夏）bobo', '被 Momo bobo', '被 Jihyo bobo', '没有人 bobo'],
    answerIndex: 0,
    category: 'sugar',
    difficulty: 'medium',
    sourceUrl: 'https://weibo.com/5261773804/EBu6Jixf9',
    sourceNote: '「生日被夏夏 bobo」',
  },
  {
    stem: '2017-04-27「小内八和小外八」形容的是两人的什么？',
    options: ['走路 / 站姿的脚型', '发型', '签名', '舞步手势'],
    answerIndex: 0,
    category: 'sugar',
    difficulty: 'hard',
    sourceUrl: 'https://weibo.com/5261773804/F0w49rpFj',
    sourceNote: '「小内八和小外八」',
  },
  {
    stem: '2017-05-14「给小鹅画小鹅」，是谁画的？',
    options: ['Sana 给 Mina（小鹅）画小鹅', 'Mina 给 Sana 画', 'Momo 画的', '粉丝画的'],
    answerIndex: 0,
    category: 'sugar',
    difficulty: 'medium',
    sourceUrl: 'https://weibo.com/7315256980/N7rEgnS4j',
    sourceNote: '「给小鹅画小鹅」',
  },
  {
    stem: '2017-05-22 被粉丝建议「直接看完速食 cut」的是哪次行程？',
    options: ['瑞士行', '日本巡演', '海边拍摄', '巴黎行'],
    answerIndex: 0,
    category: 'sugar',
    difficulty: 'easy',
    sourceUrl: 'https://weibo.com/7767393204/5335552253500914',
    sourceNote: '「瑞士行」',
  },
  {
    stem: '2017-07-08「TT 的 bobo」发生在什么场合？',
    options: ['TT 相关舞台 / 活动上', '机场', '宿舍', '采访'],
    answerIndex: 0,
    category: 'sugar',
    difficulty: 'medium',
    sourceUrl: 'https://weibo.com/5261773804/FbsAsbL8T',
    sourceNote: '「TT 的 bobo」',
  },
  {
    stem: '2017-07-15 的「强制 bobo」是谁主动？',
    options: ['Sana 主动 bobo Mina', 'Mina 主动 bobo Sana', 'Momo 加入', '两人被成员 bobo'],
    answerIndex: 0,
    category: 'sugar',
    difficulty: 'medium',
    sourceUrl: 'https://weibo.com/5261773804/FcuygzHx9',
    sourceNote: '「强制 bobo」',
  },
  {
    stem: '2017-10-11 粉丝据当天互动得出的结论是？',
    options: ['两人“一起睡了”', '两人吵架了', '两人换宿舍了', '两人一起回国'],
    answerIndex: 0,
    category: 'sugar',
    difficulty: 'hard',
    sourceUrl: 'https://weibo.com/7767393204/5332543521161434',
    sourceNote: '「一起睡了」',
  },

  // ===================== Part B · 糖点细节（2018—2019）=====================

  {
    stem: '2018-01-15 的照片里，两人的姿势是？',
    options: ['Sana 躺在 Mina 身上 / 上面', 'Mina 躺在 Sana 身上', '两人背对背坐着', '两人在下腰'],
    answerIndex: 0,
    category: 'sugar',
    difficulty: 'medium',
    sourceUrl: 'https://weibo.com/5635875812/FErpjl7IK',
    sourceNote: '「纱躺在南上面」',
  },
  {
    stem: '2018 年情人节（02-14）这张照片里，Sana 在对 Mina 做什么？',
    options: ['摸摸头', '送巧克力', '比心', 'bobo'],
    answerIndex: 0,
    category: 'sugar',
    difficulty: 'easy',
    sourceUrl: 'https://weibo.com/5635875812/Gj5AD3lxA',
    sourceNote: '「摸摸头」',
  },
  {
    stem: '2018-02-22 某支 MV 里两人的造型是？',
    options: ['穿着睡衣的“两小只”', '礼服', '校服', '运动服'],
    answerIndex: 0,
    category: 'sugar',
    difficulty: 'medium',
    sourceUrl: 'https://weibo.com/5261773804/G4lIa52Qi',
    sourceNote: '「mv 里的睡衣两小只」',
  },
  {
    stem: '2018-04-20 的互动名场面是？',
    options: ['捏脸', '掰手腕', '击掌', '梳头'],
    answerIndex: 0,
    category: 'sugar',
    difficulty: 'easy',
    sourceUrl: 'https://weibo.com/5261773804/5273922545125389',
    sourceNote: '「捏脸」',
  },
  {
    stem: '2018-05-15 除了 TT 啵啵，Sana 还做了什么被粉丝拍下？',
    options: ['“训”了 Mina（企鹅）一顿', '教 Mina 跳舞', '给 Mina 做饭', '帮 Mina 拎包'],
    answerIndex: 0,
    category: 'sugar',
    difficulty: 'hard',
    sourceUrl: 'https://weibo.com/5550799291/GgUuHAJcq',
    sourceNote: '「TT 啵啵 + 训企鹅」',
  },
  {
    stem: '2018-08-20「抢颈枕」的结局是？',
    options: ['最后两人还是一起坐了', 'Sana 抢到了', 'Mina 抢到了', '颈枕被没收'],
    answerIndex: 0,
    category: 'sugar',
    difficulty: 'medium',
    sourceUrl: 'https://weibo.com/5635875812/GvuvllPdD',
    sourceNote: '「抢颈枕坐最后还是一起坐了」',
  },
  {
    stem: '2018-09-17 的照片里，Sana 是什么姿势？',
    options: ['枕在 Mina 的腿上', '靠在 Mina 肩上', '躺在地上', '坐在 Mina 对面'],
    answerIndex: 0,
    category: 'sugar',
    difficulty: 'medium',
    sourceUrl: 'https://weibo.com/1745283033/GzNIQ8h8j',
    sourceNote: '「枕在南腿上的纱」',
  },
  {
    stem: '2018-09-19 被粉丝调侃「假的早安吻」，同框还出现了什么“真”的东西？',
    options: ['真·萌化妆包', '真的早餐', '真的花', '真的礼物'],
    answerIndex: 0,
    category: 'sugar',
    difficulty: 'hard',
    sourceUrl: 'https://weibo.com/5689958174/GA3t93nn3',
    sourceNote: '「假的早安吻和真萌化妆包」',
  },
  {
    stem: '2018-11-25，是谁给谁织了东西？',
    options: ['Mina 给 Sana（姐姐）织了东西', 'Sana 给 Mina 织', 'Momo 给两人织', '其实是粉丝织的'],
    answerIndex: 0,
    category: 'sugar',
    difficulty: 'medium',
    sourceUrl: 'https://weibo.com/5689958174/H4qt63kyL',
    sourceNote: '「给姐姐织了东西」',
  },
  {
    stem: '2019-03-15 的名场面里，Sana 在 Mina 身后做什么？',
    options: ['身后抱 / 闻闻妹妹', '帮她梳头', '帮她化妆', '吓她一跳'],
    answerIndex: 0,
    category: 'sugar',
    difficulty: 'medium',
    sourceUrl: 'https://weibo.com/5689958174/Hl4zftcFB',
    sourceNote: '「身后抱 / 闻闻妹妹」',
  },
  {
    stem: '2019-03-24（Mina 生日）被粉丝标注为「darling & honey」，这一天还有？',
    options: ['生日合照', '回归舞台', '机场图', '采访'],
    answerIndex: 0,
    category: 'sugar',
    difficulty: 'medium',
    sourceUrl: 'https://weibo.com/5635875812/HmqZk9lTy',
    sourceNote: '「darling & honey」',
  },
  {
    stem: '2019-03-30「讨啵啵大成功」，是谁讨到了 bobo？',
    options: ['Sana 向 Mina 讨 bobo 并大成功', 'Mina 向 Sana 讨', 'Momo 讨到了', '两人都没讨到'],
    answerIndex: 0,
    category: 'sugar',
    difficulty: 'medium',
    sourceUrl: 'https://weibo.com/5635875812/HnltSpno1',
    sourceNote: '「讨啵啵大成功」',
  },
  {
    stem: '2019-04-25「玩妹妹高马尾的坏姐姐」，这位“坏姐姐”是？',
    options: ['Sana 玩 Mina 的高马尾', 'Mina 玩 Sana', 'Nayeon 玩 Mina', 'Jihyo 玩 Sana'],
    answerIndex: 0,
    category: 'sugar',
    difficulty: 'medium',
    sourceUrl: 'https://weibo.com/1745283033/HroEhFJZg',
    sourceNote: '「玩妹妹高马尾的坏姐姐」',
  },
  {
    stem: '2019 年 8 月，Sana 兴奋地对 Mina 喊「米娜呀我们拿奖了」，这是在哪类场合？',
    options: ['颁奖礼 / 获奖之后', '机场', '演唱会结束', '直播'],
    answerIndex: 0,
    category: 'sugar',
    difficulty: 'medium',
    sourceUrl: 'https://weibo.com/5122673955/I0eTV0i8Z',
    sourceNote: '「米娜呀我们拿奖了」',
  },
  {
    stem: '2019-11-11 Sana 形容 Mina「知道所有东西」，把她比作什么？',
    options: ['谷歌（Google）', '百科全书', '老师', '导航'],
    answerIndex: 0,
    category: 'sugar',
    difficulty: 'medium',
    sourceUrl: 'https://weibo.com/5635875812/IfJiQv6sL',
    sourceNote: '「柴眼里米娜像谷歌」',
  },
  {
    stem: '2019 年最后一天（12-31），两人被记录下的环节是？',
    options: ['给对方的留言', '交换礼物', '跨年舞台', '一起看烟花'],
    answerIndex: 0,
    category: 'sugar',
    difficulty: 'medium',
    sourceUrl: 'https://weibo.com/1745283033/4455483966233827',
    sourceNote: '「给对方的留言」',
  },

  // ===================== Part B · 糖点细节（2023—2026）=====================

  {
    stem: '2023-03-13，Mina 被问“想从 Sana 那里得到什么生日礼物”，她的回答是？',
    options: ['项链', '啵啵', '糖果', '花'],
    answerIndex: 1,
    category: 'sugar',
    difficulty: 'medium',
    sourceUrl: 'https://m.weibo.cn/detail/4878934896807682',
    sourceNote: '「生日礼物想从杀下那里得到什么呢」「想要啵啵」',
  },
  {
    stem: '《Masterpiece》中 Mina 和 Sana 有著名双人舞，除了「It\'s not easy for you」，还有哪一首？',
    options: ['Do not touch', 'Funny Valentine', 'Behind The Curtain', 'Rewind You'],
    answerIndex: 1,
    category: 'sugar',
    difficulty: 'medium',
    sourceUrl: 'https://m.weibo.cn/detail/4926393408817346',
    sourceNote: '「Funny Valentine 双人舞」',
  },
  {
    stem: '2024-08-16 的名场面，Sana 对 Mina 说「爱你＿＿」？',
    options: ['一辈子', '到永远', '每一天', '不后悔'],
    answerIndex: 0,
    category: 'sugar',
    difficulty: 'medium',
    sourceUrl: 'https://m.weibo.cn/detail/5068043895964404',
    sourceNote: '「爱你一辈子」',
  },
  {
    stem: '2024-08-16 曝光的 Mina 手机备注是？',
    options: ['米糖mori🐧', '米糖🐧', '纱糖', 'Minari'],
    answerIndex: 0,
    category: 'sugar',
    difficulty: 'hard',
    sourceUrl: 'https://m.weibo.cn/detail/5068051385156638',
    sourceNote: 'B 只差 mori 最易混；「纱糖」是 Sana 的备注',
  },
  {
    stem: '2024-12-29（Sana 生日前后），Mina 对 Sana 的告白是？',
    options: ['新年快乐', '你知道我非常非常爱你吧？', '礼物收到了吗', '许个愿吧'],
    answerIndex: 1,
    category: 'sugar',
    difficulty: 'medium',
    sourceUrl: 'https://m.weibo.cn/detail/5117063993233909',
    sourceNote: '「你知道我非常非常爱你吧？」',
  },
  {
    stem: '2023-01-15 被粉丝概括为「坐旁边就要＿＿」？',
    options: ['摸摸', '说话', '拍照', '分享零食'],
    answerIndex: 0,
    category: 'sugar',
    difficulty: 'medium',
    sourceUrl: 'https://m.weibo.cn/detail/4858295096181231',
    sourceNote: '「坐旁边就要摸摸」',
  },
  {
    stem: '2023-03-29，Sana 偷夸「咪娜今天特别清纯呢」，结果？',
    options: ['被当场抓包', 'Mina 没听见', '被 Momo 打断', '上了热搜'],
    answerIndex: 0,
    category: 'sugar',
    difficulty: 'medium',
    sourceUrl: 'https://m.weibo.cn/detail/4884675007610951',
    sourceNote: '「偷夸咪娜被当场抓包」',
  },
  {
    stem: '2023-04-15，Sana 形容自己「对于咪娜来说是＿＿」？',
    options: ['磁铁', '影子', '太阳', '枕头'],
    answerIndex: 0,
    category: 'sugar',
    difficulty: 'medium',
    sourceUrl: 'https://m.weibo.cn/detail/4890746983026822',
    sourceNote: '「我对于咪娜来说是磁铁」',
  },
  {
    stem: '2023-07-07「企鹅举小狗」，粉丝由此发现 “Hug” 原来是什么意思？',
    options: ['抱起来的意思', '亲亲的意思', '打招呼', '转圈'],
    answerIndex: 0,
    category: 'sugar',
    difficulty: 'hard',
    sourceUrl: 'https://m.weibo.cn/detail/4920829538205961',
    sourceNote: '「企鹅举小狗（Hug 原来是抱起来的意思）」',
  },
  {
    stem: '2023-10-06 除了「看什么笑这么开心」，同框还出现了哪句著名配文？',
    options: ['是的，我们结婚了', '我们分手吧', '生日快乐', '晚安宝贝'],
    answerIndex: 0,
    category: 'sugar',
    difficulty: 'medium',
    sourceUrl: 'https://m.weibo.cn/detail/4953903664467284',
    sourceNote: '「是的我们结婚了」',
  },
  {
    stem: '2024-03-15 被粉丝拍下「小猫小狗＿＿」？',
    options: ['缩在一起睡了', '一起吃饭', '一起跳舞', '一起回国'],
    answerIndex: 0,
    category: 'sugar',
    difficulty: 'medium',
    sourceUrl: 'https://m.weibo.cn/detail/5012236617385805',
    sourceNote: '「小猫小狗缩在一起睡了」',
  },
  {
    stem: '2024-08-16，Mina 叫 Sana 半夜去哪里约会？',
    options: ['兔子公园', '图书馆', '海边', '屋顶'],
    answerIndex: 0,
    category: 'sugar',
    difficulty: 'hard',
    sourceUrl: 'https://m.weibo.cn/detail/5068093065266117',
    sourceNote: '「小咪叫小狗半夜去兔子公园约会」',
  },
  {
    stem: '2024-11-17，两人手牵手说的是？',
    options: ['我们是 37', '我们是 46', '晚安', '再见'],
    answerIndex: 0,
    category: 'sugar',
    difficulty: 'medium',
    sourceUrl: 'https://m.weibo.cn/detail/5101730572536442',
    sourceNote: '「手牵手说“我们是 37”」',
  },
  {
    stem: '2024 年跨年夜（12-31），Mina 给 Sana 的留言开头是？',
    options: ['纱糖生日快乐！可爱的撒娜，爱你', '新年快乐，再见', '礼物在桌上', '早点休息'],
    answerIndex: 0,
    category: 'sugar',
    difficulty: 'hard',
    sourceUrl: 'https://m.weibo.cn/detail/5117441254359360',
    sourceNote: '「纱糖生日快乐！可爱的撒娜，爱你」',
  },
  {
    stem: '2024-07-12 粉丝记录「在大巴上就喜欢＿＿」？',
    options: ['坐一起', '睡觉', '唱歌', '看风景'],
    answerIndex: 0,
    category: 'sugar',
    difficulty: 'medium',
    sourceUrl: 'https://m.weibo.cn/detail/5055360148705133',
    sourceNote: '「在大巴上就喜欢坐一起」',
  },
  {
    stem: '2025-08-24 被粉丝直接命名为「＿＿」的名场面？',
    options: ['37 抱抱', '37 吵架', '37 机场', '37 初雪'],
    answerIndex: 0,
    category: 'sugar',
    difficulty: 'easy',
    sourceUrl: 'https://m.weibo.cn/detail/5203221884960845',
    sourceNote: '「37 抱抱」',
  },
  {
    stem: '2025-09-17 被形容为「两只小动物」，同条还记录了什么调皮事？',
    options: ['拆下娃娃的裙子', '藏起话筒', '学对方说话', '关掉摄像机'],
    answerIndex: 0,
    category: 'sugar',
    difficulty: 'hard',
    sourceUrl: 'https://m.weibo.cn/detail/5211923320932458',
    sourceNote: '「拆下娃娃的裙子」',
  },
  {
    stem: '2025-12-14 被粉丝配上「＿＿」标题的名场面？',
    options: ['婚礼进行曲', '圣诞歌', '生日歌', '告别曲'],
    answerIndex: 0,
    category: 'sugar',
    difficulty: 'medium',
    sourceUrl: 'https://m.weibo.cn/detail/5243922624545828',
    sourceNote: '「婚礼进行曲」',
  },
  {
    stem: '粉丝为两人设立的纪念日「3.7 Day」，2026 年的庆祝是哪天？',
    options: ['2026-03-07', '2026-03-08', '2026-07-03', '2026-03-24'],
    answerIndex: 0,
    category: 'sugar',
    difficulty: 'hard',
    sourceUrl: 'https://m.weibo.cn/detail/5274194552296801',
    sourceNote: '「Happy 3.7 Day」',
  },
  {
    stem: '2026-03-08 的名场面被概括为「＿＿的两小只」？',
    options: ['黏在一起', '背对背', '刚睡醒', '认真工作'],
    answerIndex: 0,
    category: 'sugar',
    difficulty: 'easy',
    sourceUrl: 'https://m.weibo.cn/detail/5274260237190627',
    sourceNote: '「黏在一起的两小只」',
  },
];
